### ISSUE TITLE
cannot find codeSystem "http://terminology.hl7.org/CodeSystem/hl7-document-format-codes

### ISSUE THREAD

**Issue by lynnfel** [IHE/FormatCode#13]
The FormatCode ValueSet contains...

  <include>
      <system
              value="http://terminology.hl7.org/CodeSystem/hl7-document-format-codes"/>
    </include>

I cannot find this CodeSystem.   What am I missing?

**Comment by JohnMoehrke** [comment]
The valueSet includes codes from HL7. You would need to go to HL7 to get these codes. The IG publisher automatically knows where to find these, and thus assembles them into the ValueSet in the FormatCode IG. 

I do not know why HL7 does not publish these codes on their terminology.hl7.org site. This is an HL7 issue.
