### ISSUE TITLE
Entries in provenance bundles - fullUrl and .id

### ISSUE THREAD

**Issue by vassilpeytchev** [IHE/FormatCode#4]
`<entry xmlns="http://hl7.org/fhir">
		<fullUrl value="http://profiles.ihe.net/fhir/ihe.formatcode.fhir/Provenance/20200724"/>
		<resource>
			<Provenance>
				<id value="formatcode-provenance-20200724"/>`

1. fullUrl must be either a valid reference to the resource, or a urn UUID, (or urn OID)
2. fullUrl and Provenance.id within the entry must match

**Comment by JohnMoehrke** [comment]
How do you suggest this is fixed? I guess there is no reason not to use UUID? It would just require the editor to generate a UUID.
