### ISSUE TITLE
Some inconsistencies in the formatCode Value Set and Code System

### ISSUE THREAD

**Issue by lynnfel** [IHE/FormatCode#7]
I have been taking a close look at our formatCode value set and codeSystem in the context of some SVCM test preparation.

This Github issue points out some inconsistencies  (my view).  You can correct any misconceptions.

First, I am looking here:  https://profiles.ihe.net/fhir/ihe.formatcode.fhir/ValueSet-formatcode.html

The “Definition” at the top includes this statement:  
“The IHE FormatCode Value set is defined to be the set of FormatCode(s) **defined by IHE** http://wiki.ihe.net/index.php?title=IHE_Format_Codes…”.  
...and that wiki page has been scrubbed (hurray) to remove the list of codes and instead include a summary including “ This FormatCode vocabulary represents:  Code System 1.3.6.1.4.1.19376.1.2.3 “  (which I believe is the equivalent of http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode).

In Sec 3.1.1.1, the "Logical Definition" of what the value set contains includes the IHE format CodeSystem, one DICOM code for the KOS manifest, and the HL7 codes for C-CDA docs (what I would expect).

**ISSUE 1:**  There is a slight incongruity between the text in the Definition and the Logical Definition.   I think the text in the Definition at the top more accurately describes the Code System http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode and not the Value Set http://ihe.net/fhir/ihe.formatcode.fhir/ValueSet/formatcode

====
Next, I am looking here https://profiles.ihe.net/fhir/ihe.formatcode.fhir/CodeSystem-formatcode.html

The “Definition: up top includes this statement:
"The IHE FormatCode code system with canonical URI of http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode is defined to be the set of [FormatCode(s) define by IHE (http://wiki.ihe.net/index.php?title=IHE_Format_Codes), ..."
And this is what I would expect for IHE’s formatCode Code System.

**ISSUE 2**   Why does IHE’s codeSystem include the deprecated concepts with  C-CDA codes having a system value of “http://terminology.hl7.org/CodeSystem/hl7-document-format-code”?    It seems like they could be removed, especially since the HL7 implementation guide you link in the description include both C-CDA 1.1 and 2.1 codes, and  only the 1.1 deprecated codes are in our format code code system

====

**ISSUE 3 (**documented here, even though “it’s not IHE’s problem”   :-)  ):
Our format code value set:    https://profiles.ihe.net/fhir/ihe.formatcode.fhir/ValueSet-formatcode.html

…includes all codes defined in http://terminology.hl7.org/CodeSystem/hl7-document-format-codes

For the life of me, I cannot find a Code System with the above canonical URI.

John says, 
well... that is 
a) Not an IHE problem
b) really strange as the IG build finds it
c) really strange because it doesn't seem to be there 
d) Not an IHE problem

Note about (c)... this link you have is a canonical URI. It is not expected to be able to produce anything in a browser. yet, often Grahame manages a huge redirect database at HL7 to redirect these things. However these codes can't be found even if one browses to http://terminology.hl7.org

I have been complaining to the HL7 terminology group for almost two years
    https://chat.fhir.org/#narrow/stream/179202-terminology/topic/CDA.20format.20code.20vocabulary

**Comment by JohnMoehrke** [comment]
1. yes, likely cleanup may be needed
2. the deprecated codes are included as part of code lifecycle management. In the wild these codes are used often. There was poor documentation prior to "right now" that these codes were defined in HL7, and not in IHE. So many people use these code values and indicate they are in the IHE system. By including them as deprecated this will warn them.
3. working on it.
