### ISSUE TITLE
update CodeSystem formatCode for IHE Parm and IHE PCC

### ISSUE THREAD

**Issue by oliveregger** [IHE/FormatCode#9]
1. IHE Pharmacy has two content profiles [IHE MTP](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_MTP.pdf) and [IHE CMA](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_CMA.pdf) which are not listed in the [CodeSystem formatCode](https://build.fhir.org/ig/IHE/FormatCode/CodeSystem-formatcode.html)

2. The formatcode urn:ihe:pcc:irc:2008 should be urn:ihe:pcc:ic:2008 according to https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_TF_Vol2.pdf, page 34.

**Comment by JohnMoehrke** [comment]
is there a need to hurry this change? is this needed this month, this quarter, this year, or next year?

**Comment by JohnMoehrke** [comment]
closed by [145d855](https://github.com/IHE/FormatCode/commit/145d85507240c3087f0cfe9dc172f0789095d80f)
already published in 1.0.0
